# Generated by Django 5.2.1 on 2026-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
