# Generated by Django 5.2.1 on 2026-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='capa',
            field=models.ImageField(upload_to='Image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='Video/'),
        ),
    ]
