# Generated by Django 5.2.1 on 2026-02-16 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_capa_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
