# Generated by Django 5.2.1 on 2026-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
