# Generated by Django 6.0.2 on 2026-02-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_trafficlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug_pt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='descricao_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='descricao_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_pt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo_pt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
